# Generated by Django 6.0.1 on 2026-02-02 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistencia',
            name='chequeo_salida',
            field=models.BooleanField(default=False),
        ),
    ]
